name: Update Release Notes

on:
  release:
    types: [published]

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Commits since previous tag
        id: get_commits
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          COMMITS=$(git log $(git describe --abbrev=0 --tags ${TAG_NAME}^)..${TAG_NAME} --pretty=format:"- %s")
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update Release Notes via gh CLI
        env:
          GH_TOKEN: ${{ secrets.GH_RELEASE_NOTES_TOKEN }}
        run: |
          gh release edit ${{ github.event.release.tag_name }} \
            --repo ${{ github.repository }} \
            --notes "${{ steps.get_commits.outputs.commits }}"
